# Generated by Django 3.2.5 on 2021-08-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('link', models.URLField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
