# Generated by Django 3.2.5 on 2021-08-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='link',
        ),
        migrations.AddField(
            model_name='training',
            name='website',
            field=models.CharField(default='Youtube', max_length=255),
        ),
    ]
