# Generated by Django 3.2.5 on 2021-08-02 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210802_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
