# Generated by Django 3.2.5 on 2021-08-02 03:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_training_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
